enum ErrorTypes {
  NOT_FOUND = 'NOT_FOUND',
  QUERY_FAILED = 'QUERY_FAILED',
  DATA_EMPTY = 'DATA_EMPTY',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  PARAM_ERROR = 'PARAM_ERROR',
  DELETE_FAILED = 'DELETE_FAILED',
  IMAGE_URL_INVALID = 'IMAGE_URL_INVALID',
}
export default ErrorTypes
